"""polished relationships and went for cascade with passive_delete instad of orm

Revision ID: 015a0f6e4c64
Revises: 1b1cbd7d141e
Create Date: 2025-10-13 19:53:33.022095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015a0f6e4c64'
down_revision: Union[str, None] = '1b1cbd7d141e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_reservations_user_id'), 'reservations', ['user_id'], unique=False)
    op.create_foreign_key(None, 'reservations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_index(op.f('ix_reservations_user_id'), table_name='reservations')
    op.drop_column('reservations', 'user_id')
    # ### end Alembic commands ###
