"""changed parking_lot fields

Revision ID: 18f83aa6d1ef
Revises: b331fa48479d
Create Date: 2025-10-14 19:55:01.995705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18f83aa6d1ef'
down_revision: Union[str, None] = 'b331fa48479d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
