"""added reservations router to main.py

Revision ID: 1b1cbd7d141e
Revises: 9a6156fae57d
Create Date: 2025-10-13 19:43:05.934962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b1cbd7d141e'
down_revision: Union[str, None] = '9a6156fae57d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
