"""Parking lots table updated

Revision ID: 5259e67717fa
Revises: 4d1242910fd4
Create Date: 2025-11-04 10:10:57.100380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5259e67717fa'
down_revision: Union[str, None] = '4d1242910fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_lots', sa.Column('location', sa.String(length=120), nullable=False))
    op.add_column('parking_lots', sa.Column('address', sa.String(length=255), nullable=False))
    op.add_column('parking_lots', sa.Column('capacity', sa.Integer(), nullable=False))
    op.add_column('parking_lots', sa.Column('reserved', sa.Integer(), nullable=False))
    op.add_column('parking_lots', sa.Column('tariff', sa.Float(), nullable=False))
    op.add_column('parking_lots', sa.Column('daytariff', sa.Float(), nullable=False))
    op.add_column('parking_lots', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('parking_lots', sa.Column('longitude', sa.Float(), nullable=False))
    op.alter_column('parking_lots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('parking_lots', 'updated_at')
    op.drop_column('parking_lots', 'timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_lots', sa.Column('timezone', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('parking_lots', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('parking_lots', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('parking_lots', 'longitude')
    op.drop_column('parking_lots', 'latitude')
    op.drop_column('parking_lots', 'daytariff')
    op.drop_column('parking_lots', 'tariff')
    op.drop_column('parking_lots', 'reserved')
    op.drop_column('parking_lots', 'capacity')
    op.drop_column('parking_lots', 'address')
    op.drop_column('parking_lots', 'location')
    # ### end Alembic commands ###
