"""removed spots entirely and only work with parking_lots

Revision ID: 83c2447f721a
Revises: 18f83aa6d1ef
Create Date: 2025-10-14 20:17:19.065373

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "83c2447f721a"
down_revision: Union[str, None] = "18f83aa6d1ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reservations", sa.Column("parking_lot_id", sa.Integer(), nullable=False)
    )
    op.drop_index("ix_reservations_spot_id", table_name="reservations")
    op.create_index(
        op.f("ix_reservations_parking_lot_id"),
        "reservations",
        ["parking_lot_id"],
        unique=False,
    )
    op.drop_constraint("reservations_spot_id_fkey", "reservations", type_="foreignkey")
    op.create_foreign_key(
        None,
        "reservations",
        "parking_lots",
        ["parking_lot_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("reservations", "spot_id")
    op.drop_index("ix_spots_lot_id", table_name="spots")
    op.drop_table("spots")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reservations",
        sa.Column("spot_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "reservations", type_="foreignkey")
    op.create_foreign_key(
        "reservations_spot_id_fkey",
        "reservations",
        "spots",
        ["spot_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_reservations_parking_lot_id"), table_name="reservations")
    op.create_index(
        "ix_reservations_spot_id", "reservations", ["spot_id"], unique=False
    )
    op.drop_column("reservations", "parking_lot_id")
    op.create_table(
        "spots",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("lot_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("label", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column("kind", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["parking_lots.id"],
            name="spots_lot_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="spots_pkey"),
    )
    op.create_index("ix_spots_lot_id", "spots", ["lot_id"], unique=False)
    # ### end Alembic commands ###
