"""Payments table added

Revision ID: 8ec7b1ded50e
Revises: 5259e67717fa
Create Date: 2025-11-11 08:32:41.023286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ec7b1ded50e'
down_revision: Union[str, None] = '5259e67717fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('transaction', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('initiator', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('hash', sa.String(length=100), nullable=True),
    sa.Column('t_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_reservation_id'), 'payments', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_payments_transaction'), 'payments', ['transaction'], unique=True)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.add_column('reservations', sa.Column('vehicle_id', sa.Integer(), nullable=False))
    op.add_column('reservations', sa.Column('start_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('reservations', sa.Column('end_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('reservations', sa.Column('cost', sa.Float(), nullable=False))
    op.create_index(op.f('ix_reservations_vehicle_id'), 'reservations', ['vehicle_id'], unique=False)
    op.create_foreign_key(None, 'reservations', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reservations', 'starts_at')
    op.drop_column('reservations', 'ends_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('ends_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('reservations', sa.Column('starts_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_index(op.f('ix_reservations_vehicle_id'), table_name='reservations')
    op.drop_column('reservations', 'cost')
    op.drop_column('reservations', 'end_time')
    op.drop_column('reservations', 'start_time')
    op.drop_column('reservations', 'vehicle_id')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_transaction'), table_name='payments')
    op.drop_index(op.f('ix_payments_reservation_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
